services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - GEMINI_SEC_KEY=${GEMINI_SEC_KEY}
    ports:
      - "8000:8000"
    networks:
      - ifrs16-network

networks:
  ifrs16-network:
    external: true